# Generated by Django 2.1.4 on 2018-12-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        ('designs', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField()),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designs.Bed')),
            ],
        ),
        migrations.CreateModel(
            name='PlantAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlantFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PlantSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('web_address', models.CharField(max_length=256)),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('latin_name', models.CharField(blank=True, max_length=128, null=True)),
                ('full_height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Full height (cm)')),
                ('full_diameter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Full diameter (cm)')),
                ('light', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Full shade'), (2, 'Partial shade'), (3, 'Shade tolerant'), (4, 'Partial sun'), (5, 'Full sun')], null=True)),
                ('water', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Watering requirements: 1 (drought tolerant) - 5 (needs regular watering)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('annual', models.BooleanField(default=False)),
                ('companions', models.ManyToManyField(related_name='_plantspecies_companions_+', to='plants.PlantSpecies')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to='plants.PlantFamily')),
                ('harvest', models.ManyToManyField(related_name='plants_to_harvest', to='planner.Month')),
                ('plant_out', models.ManyToManyField(related_name='plants_to_plant_out', to='planner.Month')),
                ('seed_indoors', models.ManyToManyField(related_name='plants_to_seed_indoors', to='planner.Month')),
                ('seed_outdoors', models.ManyToManyField(related_name='plants_to_seed_outdoors', to='planner.Month')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_species', to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.PlantSource'),
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plants.PlantSpecies'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='plants',
            field=models.ManyToManyField(to='plants.Plant'),
        ),
    ]
